namespace :one_timers do
  task :seed_regions => :environment do
    Region.create(:country_id => 1, :region_code => 'AB')
    Region.create(:country_id => 1, :region_code => 'BC')
    Region.create(:country_id => 1, :region_code => 'MB')
    Region.create(:country_id => 1, :region_code => 'NB')
    Region.create(:country_id => 1, :region_code => 'NL')
    Region.create(:country_id => 1, :region_code => 'NS')
    Region.create(:country_id => 1, :region_code => 'NU')
    Region.create(:country_id => 1, :region_code => 'ON')
    Region.create(:country_id => 1, :region_code => 'PE')
    Region.create(:country_id => 1, :region_code => 'QC')
    Region.create(:country_id => 1, :region_code => 'SK')
    Region.create(:country_id => 1, :region_code => 'NT')
    Region.create(:country_id => 1, :region_code => 'YT')
    Region.create(:country_id => 2, :region_code => 'AK')
    Region.create(:country_id => 2, :region_code => 'AL')
    Region.create(:country_id => 2, :region_code => 'AR')
    Region.create(:country_id => 2, :region_code => 'AS')
    Region.create(:country_id => 2, :region_code => 'AZ')
    Region.create(:country_id => 2, :region_code => 'CA')
    Region.create(:country_id => 2, :region_code => 'CO')
    Region.create(:country_id => 2, :region_code => 'CT')
    Region.create(:country_id => 2, :region_code => 'DC')
    Region.create(:country_id => 2, :region_code => 'DE')
    Region.create(:country_id => 2, :region_code => 'FL')
    Region.create(:country_id => 2, :region_code => 'FM')
    Region.create(:country_id => 2, :region_code => 'GA')
     Region.create(:country_id => 2, :region_code => 'GU')
     Region.create(:country_id => 2, :region_code => 'HI')
     Region.create(:country_id => 2, :region_code => 'IA')
     Region.create(:country_id => 2, :region_code => 'ID')
     Region.create(:country_id => 2, :region_code => 'IL')
     Region.create(:country_id => 2, :region_code => 'IN')
     Region.create(:country_id => 2, :region_code => 'KS')
     Region.create(:country_id => 2, :region_code => 'KY')
     Region.create(:country_id => 2, :region_code => 'LA')
     Region.create(:country_id => 2, :region_code => 'MA')
     Region.create(:country_id => 2, :region_code => 'MD')
     Region.create(:country_id => 2, :region_code => 'ME')
     Region.create(:country_id => 2, :region_code => 'MH')
     Region.create(:country_id => 2, :region_code => 'MI')
     Region.create(:country_id => 2, :region_code => 'MN')
     Region.create(:country_id => 2, :region_code => 'MO')
     Region.create(:country_id => 2, :region_code => 'MP')
     Region.create(:country_id => 2, :region_code => 'MS')
     Region.create(:country_id => 2, :region_code => 'MT')
     Region.create(:country_id => 2, :region_code => 'NC')
     Region.create(:country_id => 2, :region_code => 'ND')
     Region.create(:country_id => 2, :region_code => 'NE',)
     Region.create(:country_id => 2, :region_code => 'NH')
     Region.create(:country_id => 2, :region_code => 'NJ')
     Region.create(:country_id => 2, :region_code => 'NM')
     Region.create(:country_id => 2, :region_code => 'NV')
     Region.create(:country_id => 2, :region_code => 'NY')
     Region.create(:country_id => 2, :region_code => 'OH')
     Region.create(:country_id => 2, :region_code => 'OK')
     Region.create(:country_id => 2, :region_code => 'OR')
     Region.create(:country_id => 2, :region_code => 'PA')
     Region.create(:country_id => 2, :region_code => 'PR')
     Region.create(:country_id => 2, :region_code => 'RI')
     Region.create(:country_id => 2, :region_code => 'SC')
     Region.create(:country_id => 2, :region_code => 'SD')
     Region.create(:country_id => 2, :region_code => 'TN')
     Region.create(:country_id => 2, :region_code => 'TX')
     Region.create(:country_id => 2, :region_code => 'UT')
     Region.create(:country_id => 2, :region_code => 'VA')
     Region.create(:country_id => 2, :region_code => 'VI')
     Region.create(:country_id => 2, :region_code => 'VT')
     Region.create(:country_id => 2, :region_code => 'WA')
     Region.create(:country_id => 2, :region_code => 'WV')
     Region.create(:country_id => 2, :region_code => 'WI')
     Region.create(:country_id => 2, :region_code => 'WY')
  end

  task :add_region_name => :environment do
    Region.where("country_id = ? AND region_code = ?", 1, "AB").first.update_attribute(:name, "Alberta")
    Region.where("country_id = ? AND region_code = ?", 1, "BC").first.update_attribute(:name, "British Colombia")
    Region.where("country_id = ? AND region_code = ?", 1, "MB").first.update_attribute(:name, "Manitoba")
    Region.where("country_id = ? AND region_code = ?", 1, "NB").first.update_attribute(:name, "New Brunswick")
    Region.where("country_id = ? AND region_code = ?", 1, "NL").first.update_attribute(:name, "Newfoundland")
    Region.where("country_id = ? AND region_code = ?", 1, "NS").first.update_attribute(:name, "Nova Scotia")
    Region.where("country_id = ? AND region_code = ?", 1, "NU").first.update_attribute(:name, "Nunavut")
    Region.where("country_id = ? AND region_code = ?", 1, "ON").first.update_attribute(:name, "Ontario")
    Region.where("country_id = ? AND region_code = ?", 1, "PE").first.update_attribute(:name, "Prince Edward Island")
    Region.where("country_id = ? AND region_code = ?", 1, "QC").first.update_attribute(:name, "Quebec")
    Region.where("country_id = ? AND region_code = ?", 1, "SK").first.update_attribute(:name, "Saskatchewan")
    Region.where("country_id = ? AND region_code = ?", 1, "NT").first.update_attribute(:name, "Northwest Territories")
    Region.where("country_id = ? AND region_code = ?", 1, "YT").first.update_attribute(:name, "Yukon Territory")
    # finish this later
    # Region.where("country_id = ? AND region_code = ?", 2, "AK").first.update_attribute(:name, "Alaska")
    # Region.where("country_id = ? AND region_code = ?", 2, "AL").first.update_attribute(:name, "Alabama")
    # Region.where("country_id = ? AND region_code = ?", 2, "AR").first.update_attribute(:name, "Arkansas")
    # Region.where("country_id = ? AND region_code = ?", 2, "AS").first.update_attribute(:name, "American Samoa")
    # Region.where("country_id = ? AND region_code = ?", 2, "AZ").first.update_attribute(:name, "Arizona")
    # Region.where("country_id = ? AND region_code = ?", 2, "CA").first.update_attribute(:name, "California")
    # Region.where("country_id = ? AND region_code = ?", 2, "CO").first.update_attribute(:name, "Colorado")
    # Region.where("country_id = ? AND region_code = ?", 2, "CT").first.update_attribute(:name, "Connecticut")
    # Region.where("country_id = ? AND region_code = ?", 2, "DC").first.update_attribute(:name, "District of Colombia")
    # Region.where("country_id = ? AND region_code = ?", 2, "DC").first.update_attribute(:name, "District of Colombia")
    # Region.where("country_id = ? AND region_code = ?", 2, "DE").first.update_attribute(:name, "Delaware")
    # Region.where("country_id = ? AND region_code = ?", 2, "FL").first.update_attribute(:name, "Florida")
    # Region.where("country_id = ? AND region_code = ?", 2, "FM").first.update_attribute(:name, "Federated States of Micronesia")
    # Region.where("country_id = ? AND region_code = ?", 2, "GA").first.update_attribute(:name, "Georgia")
    # Region.where("country_id = ? AND region_code = ?", 2, "GU").first.update_attribute(:name, "Guam")
    # Region.where("country_id = ? AND region_code = ?", 2, "HI").first.update_attribute(:name, "Hawaii")
    # Region.where("country_id = ? AND region_code = ?", 2, "IA").first.update_attribute(:name, "Iowa")
    # Region.where("country_id = ? AND region_code = ?", 2, "ID").first.update_attribute(:name, "Idaho")
    # Region.where("country_id = ? AND region_code = ?", 2, "IL").first.update_attribute(:name, "Illinois")
    # Region.where("country_id = ? AND region_code = ?", 2, "IN").first.update_attribute(:name, "Indiana")
    # Region.where("country_id = ? AND region_code = ?", 2, "KS").first.update_attribute(:name, "Kansas")
    # Region.where("country_id = ? AND region_code = ?", 2, "KY").first.update_attribute(:name, "Kentucky")
    # Region.where("country_id = ? AND region_code = ?", 2, "LA").first.update_attribute(:name, "Louisiana")
    # Region.where("country_id = ? AND region_code = ?", 2, "MA").first.update_attribute(:name, "Massachusetts")
    # Region.where("country_id = ? AND region_code = ?", 2, "MD").first.update_attribute(:name, "Maryland")
    # Region.where("country_id = ? AND region_code = ?", 2, "ME").first.update_attribute(:name, "Maine")
    # Region.where("country_id = ? AND region_code = ?", 2, "MH").first.update_attribute(:name, "Marshall Islands")
    # Region.where("country_id = ? AND region_code = ?", 2, "MI").first.update_attribute(:name, "Michigan")
    # Region.where("country_id = ? AND region_code = ?", 2, "MN").first.update_attribute(:name, "Minnesota")
    # Region.where("country_id = ? AND region_code = ?", 2, "MO").first.update_attribute(:name, "Missouri")
    # Region.where("country_id = ? AND region_code = ?", 2, "MT").first.update_attribute(:name, "Montana")
    # Region.where("country_id = ? AND region_code = ?", 2, "MI").first.update_attribute(:name, "Michigan")
  end

end